"""Index Message

Revision ID: 25948b2ce952
Revises: ace2aea2de63
Create Date: 2024-11-10 11:32:21.823175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25948b2ce952'
down_revision = 'ace2aea2de63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('message_honeypot_triggered_sent_idx', ['honeypot_triggered', 'sent'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('message_honeypot_triggered_sent_idx')

    # ### end Alembic commands ###
