"""Initial

Revision ID: c12241c6e237
Revises:
Create Date: 2024-11-10 15:02:46.156586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12241c6e237'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_ip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_addr', sa.String(length=120), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banned_ip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banned_ip_ip_addr'), ['ip_addr'], unique=True)

    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('ip_addr', sa.String(length=120), nullable=False),
    sa.Column('user_agent', sa.String(length=120), nullable=False),
    sa.Column('honeypot_triggered', sa.Boolean(), nullable=False),
    sa.Column('received', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rejected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_processed'), ['processed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_processed'))

    op.drop_table('message')
    with op.batch_alter_table('banned_ip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banned_ip_ip_addr'))

    op.drop_table('banned_ip')
    # ### end Alembic commands ###
